export const CALENDAR_GRID_MIN_WIDTH = "1008px";
export const CALENDAR_WEEK_COUNT_FOUR = 4;
export const CALENDAR_WEEK_COUNT_FIVE = 5;
export const CALENDAR_WEEK_COUNT_SIX = 6;

export const CALENDAR_WEEK_COUNT_TO_COMPACT = 6;
export const CALENDAR_LABEL_HEIGHT_PX = 44;
export const CALENDAR_LABEL_X_PADDING = 350;
export const CALENDAR_LABEL_Y_PADDING = 200;

export const CALENDAR_COMPACT_MIN_ROW_HEIGHT = 90;
export const CALENDAR_COMPACT_MAX_ROW_HEIGHT = 100;
export const CALENDAR_FOUR_WEEK_MAX_ROW_HEIGHT = 160;
export const CALENDAR_FIVE_WEEK_MAX_ROW_HEIGHT = 136;
export const CALENDAR_SIX_OR_MORE_WEEK_MAX_ROW_HEIGHT = 120;

export const CALENDAR_ROW_HEIGHT_VIEWPORT_OFFSET = 260;
