plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.9'
    id 'io.spring.dependency-management' version '1.1.7'
}

jacoco {
    toolVersion = "0.8.10"
}

group = 'com.moong'
version = '0.0.1-SNAPSHOT'
description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-api:2.6.0'

    //WebClient
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    //Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    //Regression
    implementation 'org.apache.commons:commons-math3:3.6.1'

    //Redisson
    implementation 'org.redisson:redisson-spring-boot-starter:3.27.0'

    implementation 'org.ow2.asm:asm:9.7'
    implementation 'org.ow2.asm:asm-tree:9.7'

    //Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //DB
    implementation 'org.flywaydb:flyway-mysql'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    //Logging
    implementation 'com.github.maricn:logback-slack-appender:1.6.1'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-gson:0.11.5'

    //Mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    //Thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    //Test
    testImplementation("com.navercorp.fixturemonkey:fixture-monkey-starter:1.1.11")
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    //Test-Container
    testImplementation 'org.testcontainers:testcontainers:1.19.3'
    testImplementation 'org.testcontainers:mysql:1.19.3'
    testImplementation 'org.testcontainers:junit-jupiter:1.19.3'
}

bootJar {
    layered {
        enabled = true
    }
}

test {
    systemProperty 'user.timezone', 'Asia/Seoul'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required.set(true)
        csv.required.set(false)
        html.required.set(false)
    }

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    "com/moong/**/dto/**"
            ])
        }))
    }
}
