import { DiseaseCode, DiseaseCostResponse } from "@/app/(sidebar)/forecast/forecast.type";

export const mockCosts: Record<DiseaseCode, DiseaseCostResponse> = {
  DER: {
    treatments: [
      {
        name: "곰팡이성 피부염",
        description: "피부 트러블, 설사·구토, 세균·바이러스 감염 등",
        minPrice: 45000,
        maxPrice: 120000,
        averagePrice: 68000,
      },
      {
        name: "아토피성 피부염",
        description: "만성적인 가려움증, 피부 발적, 각질 등",
        minPrice: 50000,
        maxPrice: 150000,
        averagePrice: 85000,
      },
      {
        name: "세균성 피부염",
        description: "농피증, 피부 감염, 화농성 병변 등",
        minPrice: 40000,
        maxPrice: 100000,
        averagePrice: 62000,
      },
      {
        name: "알레르기성 피부염",
        description: "음식 알레르기, 환경 알레르기로 인한 피부 반응",
        minPrice: 55000,
        maxPrice: 130000,
        averagePrice: 78000,
      },
      {
        name: "외이염",
        description: "귀 가려움, 분비물, 악취 등",
        minPrice: 35000,
        maxPrice: 80000,
        averagePrice: 52000,
      },
    ],
  },
  OCU: {
    treatments: [
      {
        name: "결막염",
        description: "눈 충혈, 분비물, 가려움증 등",
        minPrice: 30000,
        maxPrice: 80000,
        averagePrice: 48000,
      },
      {
        name: "각막궤양",
        description: "각막 손상, 눈 통증, 시력 저하 등",
        minPrice: 80000,
        maxPrice: 250000,
        averagePrice: 145000,
      },
      {
        name: "백내장",
        description: "수정체 혼탁, 시력 감소 등",
        minPrice: 500000,
        maxPrice: 1500000,
        averagePrice: 850000,
      },
      {
        name: "녹내장",
        description: "안압 상승, 시신경 손상 등",
        minPrice: 200000,
        maxPrice: 600000,
        averagePrice: 380000,
      },
    ],
  },
  HEM: {
    treatments: [
      {
        name: "빈혈",
        description: "혈색소 감소, 무기력, 식욕 저하 등",
        minPrice: 50000,
        maxPrice: 200000,
        averagePrice: 95000,
      },
      {
        name: "혈소판 감소증",
        description: "출혈 경향, 멍, 점상 출혈 등",
        minPrice: 100000,
        maxPrice: 400000,
        averagePrice: 220000,
      },
      {
        name: "면역매개성 용혈성 빈혈",
        description: "자가면역으로 인한 적혈구 파괴",
        minPrice: 200000,
        maxPrice: 800000,
        averagePrice: 450000,
      },
      {
        name: "백혈병",
        description: "백혈구 이상 증식, 면역 저하 등",
        minPrice: 300000,
        maxPrice: 1000000,
        averagePrice: 580000,
      },
    ],
  },
  MUS: {
    treatments: [
      {
        name: "슬개골 탈구",
        description: "무릎 관절 이상, 절뚝거림, 통증 등",
        minPrice: 800000,
        maxPrice: 2500000,
        averagePrice: 1500000,
      },
      {
        name: "고관절 이형성증",
        description: "고관절 발육 이상, 보행 장애 등",
        minPrice: 1000000,
        maxPrice: 3000000,
        averagePrice: 1800000,
      },
      {
        name: "십자인대 파열",
        description: "무릎 관절 불안정, 급성 파행 등",
        minPrice: 1200000,
        maxPrice: 3500000,
        averagePrice: 2200000,
      },
      {
        name: "추간판 질환",
        description: "디스크 탈출, 신경 압박, 마비 등",
        minPrice: 1500000,
        maxPrice: 5000000,
        averagePrice: 2800000,
      },
    ],
  },
  NEU: {
    treatments: [
      {
        name: "뇌전증(간질)",
        description: "발작, 경련, 의식 소실 등",
        minPrice: 100000,
        maxPrice: 500000,
        averagePrice: 250000,
      },
      {
        name: "전정기관 질환",
        description: "어지러움, 안구 진탕, 균형 장애 등",
        minPrice: 80000,
        maxPrice: 300000,
        averagePrice: 165000,
      },
      {
        name: "뇌수막염",
        description: "뇌막 염증, 고열, 경부 강직 등",
        minPrice: 200000,
        maxPrice: 800000,
        averagePrice: 420000,
      },
      {
        name: "말초신경병증",
        description: "사지 마비, 근력 약화, 감각 이상 등",
        minPrice: 150000,
        maxPrice: 600000,
        averagePrice: 320000,
      },
    ],
  },
  RES: {
    treatments: [
      {
        name: "기관지염",
        description: "기침, 가래, 호흡 곤란 등",
        minPrice: 40000,
        maxPrice: 120000,
        averagePrice: 72000,
      },
      {
        name: "폐렴",
        description: "고열, 기침, 호흡 곤란, 식욕 저하 등",
        minPrice: 100000,
        maxPrice: 400000,
        averagePrice: 220000,
      },
      {
        name: "기관 허탈",
        description: "거위 울음소리 기침, 호흡 곤란 등",
        minPrice: 80000,
        maxPrice: 300000,
        averagePrice: 165000,
      },
      {
        name: "천식",
        description: "발작성 호흡 곤란, 천명음 등",
        minPrice: 60000,
        maxPrice: 200000,
        averagePrice: 115000,
      },
    ],
  },
  CAR: {
    treatments: [
      {
        name: "심장판막 질환",
        description: "심잡음, 운동 불내성, 기침 등",
        minPrice: 150000,
        maxPrice: 500000,
        averagePrice: 280000,
      },
      {
        name: "심근병증",
        description: "심장 비대, 부정맥, 호흡 곤란 등",
        minPrice: 200000,
        maxPrice: 800000,
        averagePrice: 450000,
      },
      {
        name: "심부전",
        description: "폐부종, 복수, 운동 불내성 등",
        minPrice: 180000,
        maxPrice: 600000,
        averagePrice: 350000,
      },
      {
        name: "부정맥",
        description: "불규칙한 심장 박동, 실신 등",
        minPrice: 120000,
        maxPrice: 400000,
        averagePrice: 230000,
      },
    ],
  },
  URI: {
    treatments: [
      {
        name: "방광염",
        description: "빈뇨, 혈뇨, 배뇨 통증 등",
        minPrice: 40000,
        maxPrice: 120000,
        averagePrice: 68000,
      },
      {
        name: "요로결석",
        description: "배뇨 장애, 혈뇨, 복통 등",
        minPrice: 200000,
        maxPrice: 800000,
        averagePrice: 420000,
      },
      {
        name: "만성 신부전",
        description: "다음다뇨, 체중 감소, 구토 등",
        minPrice: 150000,
        maxPrice: 500000,
        averagePrice: 280000,
      },
      {
        name: "급성 신부전",
        description: "무뇨, 구토, 탈수, 무기력 등",
        minPrice: 300000,
        maxPrice: 1000000,
        averagePrice: 580000,
      },
    ],
  },
  REP: {
    treatments: [
      {
        name: "자궁축농증",
        description: "자궁 내 농 축적, 발열, 식욕 저하 등",
        minPrice: 500000,
        maxPrice: 1500000,
        averagePrice: 850000,
      },
      {
        name: "전립선 비대",
        description: "배변 곤란, 혈뇨, 보행 이상 등",
        minPrice: 100000,
        maxPrice: 400000,
        averagePrice: 220000,
      },
      {
        name: "고환 종양",
        description: "고환 비대, 호르몬 이상 등",
        minPrice: 300000,
        maxPrice: 1000000,
        averagePrice: 580000,
      },
      {
        name: "유선 종양",
        description: "유선 부위 종괴, 통증 등",
        minPrice: 400000,
        maxPrice: 1200000,
        averagePrice: 720000,
      },
    ],
  },
  END: {
    treatments: [
      {
        name: "당뇨병",
        description: "다음다뇨, 체중 감소, 백내장 등",
        minPrice: 100000,
        maxPrice: 400000,
        averagePrice: 220000,
      },
      {
        name: "갑상선 기능 저하증",
        description: "무기력, 비만, 피부 문제 등",
        minPrice: 80000,
        maxPrice: 250000,
        averagePrice: 145000,
      },
      {
        name: "갑상선 기능 항진증",
        description: "체중 감소, 식욕 증가, 구토 등",
        minPrice: 100000,
        maxPrice: 350000,
        averagePrice: 195000,
      },
      {
        name: "부신피질 기능 항진증",
        description: "다음다뇨, 복부 팽만, 탈모 등",
        minPrice: 150000,
        maxPrice: 500000,
        averagePrice: 280000,
      },
    ],
  },
  INF: {
    treatments: [
      {
        name: "파보바이러스 감염증",
        description: "구토, 혈변, 탈수, 고열 등",
        minPrice: 200000,
        maxPrice: 800000,
        averagePrice: 450000,
      },
      {
        name: "켄넬코프",
        description: "기침, 콧물, 발열 등",
        minPrice: 50000,
        maxPrice: 150000,
        averagePrice: 85000,
      },
      {
        name: "고양이 범백혈구 감소증",
        description: "고열, 구토, 설사, 탈수 등",
        minPrice: 200000,
        maxPrice: 700000,
        averagePrice: 400000,
      },
      {
        name: "심장사상충",
        description: "기침, 운동 불내성, 호흡 곤란 등",
        minPrice: 300000,
        maxPrice: 1500000,
        averagePrice: 750000,
      },
    ],
  },
  GAS: {
    treatments: [
      {
        name: "급성 위장염",
        description: "구토, 설사, 식욕 저하 등",
        minPrice: 40000,
        maxPrice: 120000,
        averagePrice: 68000,
      },
      {
        name: "췌장염",
        description: "구토, 복통, 식욕 저하, 설사 등",
        minPrice: 150000,
        maxPrice: 500000,
        averagePrice: 280000,
      },
      {
        name: "장폐색",
        description: "구토, 복통, 배변 장애 등",
        minPrice: 500000,
        maxPrice: 2000000,
        averagePrice: 1100000,
      },
      {
        name: "염증성 장 질환",
        description: "만성 구토, 설사, 체중 감소 등",
        minPrice: 100000,
        maxPrice: 400000,
        averagePrice: 220000,
      },
    ],
  },
};
