/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/pet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 반려동물 정보 조회
     * @description 로그인한 회원의 반려동물 정보를 조회합니다.
     */
    get: operations["findPetInfo"];
    /**
     * 반려동물 정보 수정
     * @description 요청으로 전달된 반려동물 정보를 수정합니다.
     */
    put: operations["updatePetInfo"];
    /**
     * 반려동물 등록
     * @description 회원이 새로운 반려동물을 등록합니다.
     */
    post: operations["savePet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/participate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 그룹 초대 참여
     * @description 초대 URL을 통해 펫 그룹에 참여합니다.
     */
    post: operations["participate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/bank": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 저금통 정보 조회
     * @description 저금통의 현재, 목표 금액을 반환합니다
     */
    get: operations["findBankInfo"];
    put?: never;
    /**
     * 저금통 생성
     * @description 로그인한 사용자가 속한 모임에
     *     목표 금액을 가진 저금통을 생성합니다.
     */
    post: operations["createBank"];
    /**
     * 저금통 깨기
     * @description 저금통을 깨고, 저축 기간과 축하 메시지를 반환합니다.
     */
    delete: operations["breakBank"];
    options?: never;
    head?: never;
    /**
     * 저금통 목표 금액 변경
     * @description 저금통 목표 금액을 변경하고, 변경된 금액을 반환합니다.
     */
    patch: operations["updateBank"];
    trace?: never;
  };
  "/api/group/bank/nudge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 재촉하기
     * @description 같은 그룹원들에게 저금하기를 재촉합니다.
     */
    post: operations["createGroupNudge"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/bank/coins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임가계부 저금통 코인 내역 반환
     * @description 저금통의 코인 내역의 정보들의 리스트를 반환합니다.
     */
    get: operations["findCoins"];
    put?: never;
    /**
     * 결제 요청 전 정보 등록 및 검증
     * @description 실제 결제 요청 전, 요청 금액의 유효성을 검증하고 고유 주문 번호(OrderId)를 생성하여 전달합니다.
     */
    post: operations["createCoinPayment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/bank/coins/fail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 결제 실패 처리
     * @description 사용자가 결제를 중단하거나 프로세스 중 오류가 발생했을 때, 생성된 결제 대기 건을 실패 처리하고 락을 해제합니다.
     */
    post: operations["paymentFailure"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/bank/coins/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 결제 성공 시 결제 확정을 위한 요청
     * @description 결제 성공 시 결제 확정을 위해 서버에 요청합니다.
     */
    post: operations["paymentSuccess"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 기간 내의 개인 소비내역 반환
     * @description 시작일/종료일을 기준으로 기간 내 개인 소비내역을 최신순으로 조회합니다.
     */
    get: operations["getMemberExpensesByPeriod"];
    put?: never;
    /**
     * 자동 카테고리 분류
     * @description 유저의 사용내역을 보고 대분류/소분류 카테고리를 자동 분류합니다
     */
    post: operations["categorizeMemberExpenses"];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 개인 소비 지출 입력
     * @description 개인 소비 내역을 생성하거나 수정하고, 삭제 대상 내역은 함께 제거합니다.
     */
    patch: operations["upsertMemberExpenses"];
    trace?: never;
  };
  "/api/auth/sse-token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Connection 토큰 발급
     * @description Connection 토큰을 발급합니다.
     */
    post: operations["issueConnectionToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 토큰 재발급
     * @description 만료된 Access Token을 Refresh Token을 사용하여 재발급합니다.
     */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description 현재 로그인된 사용자를 로그아웃 처리하고 Refresh Token을 무효화합니다.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그인
     * @description 구글 OAuth 인증 후 로그인을 처리합니다.
     *     Authorization 헤더로 Access Token, Set-Cookie로 Refresh Token을 반환합니다.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/member/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 회원 프로필 업데이트 요청
     * @description 회원 프로필을 업데이트합니다.
     */
    patch: operations["updateProfile"];
    trace?: never;
  };
  "/api/member/name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 회원 닉네임 업데이트 요청
     * @description 회원 닉네임을 업데이트합니다.
     */
    patch: operations["updateName"];
    trace?: never;
  };
  "/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 월간 레포트 발송
     * @description 즉석 월간 레포트 발송
     */
    get: operations["sendThisMonthReport"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pet-medical-ai": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["refresh_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/expenses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 기간 내의 개인 소비내역 반환 V2
     * @description 시작일/종료일을 기준으로 기간 내 개인 소비내역을 페이징으로 조회합니다.
     */
    get: operations["getMemberExpensesByPeriodV2"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 알림을 조회합니다.
     * @description 현재 참여한 그룹에서 발생한 알림을 조회합니다.
     */
    get: operations["findNotification"];
    put?: never;
    post?: never;
    /**
     * 다중 알림을 삭제합니다.
     * @description 현재 참여한 그룹에서 발생한 알림을 다중 삭재합니다.
     */
    delete: operations["deleteNotification"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notifications/count": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 읽지 않은 알림 개수를 조회합니다.
     * @description 현재 자신이 읽지 않은 알림 개수를 조회합니다.
     */
    get: operations["countNotification"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/member": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 회원 정보 반환
     * @description 회원 닉네임과 이미지 url을 반환합니다.
     */
    get: operations["findMember"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/sse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SSE 연결
     * @description 그룹 관련 이벤트를 받을 수 있도록 서버와 SSE 연결을 생성합니다.
     *     - Authorization 헤더에 Connection 토큰을 Bearer 형식으로 전달해야 합니다.
     *     - 응답은 text/event-stream 스트림이며, 연결이 유지됩니다.
     */
    get: operations["subscribe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/statistics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 그룹 질병 통계 조회
     * @description 회원이 속한 그룹의 질병별 연도 통계 데이터를 조회합니다.
     */
    get: operations["findGroupDieseaseStatistics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 그룹 의사 권장사항 반환
     * @description 로그인한 사용자가 속한 모임의 반려동물 AI 의료 권장사항과
     *     내년 연간 예상 비용을 조회합니다.
     */
    get: operations["getGroupMedicalInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/disease": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 올해 기준 발병확률 순 질병 목록 반환
     * @description 사용자의 펫 데이터를 통해 가장 주의해야할 질병부터 순서대로 반환합니다.
     */
    get: operations["findPetDiseaseRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/disease/cost": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 질병의 의료비 데이터 리스트 반환
     * @description 특정 질병의 치료법들에 대해 각 치료법의 진료명, 상세 진료 설명,
     *     그리고 치료비의 최소·최대·평균값을 조회합니다.
     */
    get: operations["getTreatment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/crews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 그룹 모임원 조회
     * @description 현재 사용자가 속한 펫 그룹의 모임원 목록과 초대 URL을 조회합니다.
     */
    get: operations["getCrews"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임 소비 내역 조회
     * @description 로그인한 사용자가 속한 모임의 소비 내역을
     *     지정한 기간(startDate ~ endDate) 기준으로 조회합니다.
     *     spendAt 기준 내림차순 > modifiedAt 기준 내림차순 정렬됩니다.
     */
    get: operations["findGroupExpenses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group/date": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 캘린더 일자별 조회
     * @description 캘린더에서 특정 날짜(spentAt)에 해당하는 그룹 소비 내역 리스트를 조회합니다.
     *     spentAt 기준 내림차순, modifiedAt 기준 내림차순으로 정렬됩니다.
     */
    get: operations["findGroupDailyExpenses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group/analysis/medical": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임 소비 내역 의료비 소분류 분석결과 조회
     * @description 로그인한 사용자가 속한 모임의 의료비 소분류별 내역을
     *     지정한 기간(startDate ~ endDate) 기준으로 조회합니다.
     *     소비내역이 가장 많은 카테고리별 순으로 내림차순 정렬됩니다.
     */
    get: operations["findMedicalCategoryAnalysis"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group/analysis/category": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임 소비 내역 카테고리 분석결과 조회
     * @description 로그인한 사용자가 속한 모임의 소비 내역을
     *     지정한 기간(startDate ~ endDate) 기준으로 조회합니다.
     *     소비내역이 가장 많은 카테고리별 순으로 내림차순 정렬됩니다.
     */
    get: operations["findCategoryAnalysis"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/compare/last-month": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지난달 소비 내역 통계
     * @description 지난달 소비내역과 의료비 소비내역 통계를 반환합니다.
     */
    get: operations["compareLastMonthExpense"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 로그아웃
     * @description 사용중인 토큰의 유효성을 판단합니다.
     */
    get: operations["validate"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/notifications/{notificationId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 단건 알림을 삭제합니다.
     * @description 현재 참여한 그룹에서 발생한 알림을 삭재합니다.
     */
    delete: operations["deleteNotification_1"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 반려동물 수정 요청 */
    PetUpdateRequest: {
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender: "M" | "F";
      /** @example 2026-02 */
      birthDate: string;
      /**
       * @description 거주 시
       * @example 서울시
       */
      city: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example [
       *       "OCU",
       *       "MUS"
       *     ]
       */
      diseases: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    ErrorResponse: {
      code?: string;
      /** Format: int32 */
      status?: number;
      message?: string;
    };
    /** @description 반려동물 수정 응답 */
    PetUpdateResponse: {
      /**
       * Format: int64
       * @description 반려동물 아이디
       * @example 1
       */
      petId?: number;
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName?: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender?: "M" | "F";
      /** @example 2026-02 */
      birthDate?: string;
      /**
       * @description 거주 시
       * @example 서울시
       */
      city?: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example [
       *       "OCU",
       *       "MUS"
       *     ]
       */
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 반려동물 생성 요청 */
    PetCreateRequest: {
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender: "M" | "F";
      /** @example 2026-02 */
      birthDate: string;
      /**
       * @description 거주 시
       * @example 서울시
       */
      city: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district: string;
      /**
       * @description 우려하는 질병 목록
       * @example OCU, MUS
       */
      diseases: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 반려동물 생성 응답 */
    PetCreateResponse: {
      /**
       * Format: int64
       * @description 반려동물 아이디
       * @example 1
       */
      petId?: number;
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName?: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender?: "M" | "F";
      /** @example 2026-02 */
      birthDate?: string;
      /**
       * @description 거주 시
       * @example 서울시
       */
      city?: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example [
       *       "OCU",
       *       "MUS"
       *     ]
       */
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 그룹 초대 요청 */
    PetGroupParticipateRequest: {
      /**
       * @description 초대코드 url
       * @example https://moong.site/invite/RRJ2A2gf4I9pSxpW6F1byH2RGEweYjpmZOGasbaXvOGtHCwq
       */
      inviteUrl: string;
    };
    /** @description 참여 완료 응답 */
    PetGroupParticipateResponse: {
      /**
       * Format: int64
       * @description 참여자 id
       * @example 1
       */
      crewId?: number;
    };
    /** @description 저금통 생성 요청 */
    BankCreateRequest: {
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 1500000
       */
      target?: number;
    };
    /** @description 저금통 생성 응답 */
    BankCreateResponse: {
      /**
       * Format: int64
       * @description 저금통 아이디
       * @example 1
       */
      bankId?: number;
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 15000000
       */
      target?: number;
    };
    /** @description 저금하기 요청 */
    CoinCreateRequest: {
      /**
       * Format: int64
       * @description 저금 금액
       * @example 5000
       */
      amount?: number;
    };
    /** @description 결제 신청 전 금액 저장 및 결제 Id 생성 요청 */
    CoinPaymentCreateResponse: {
      /**
       * Format: uuid
       * @description 결제 Id
       * @example 8973f452-cabc-4098-bdd9-d32737c86a33
       */
      orderId?: string;
      /**
       * Format: int64
       * @description 결제 금액
       * @example 1000
       */
      amount?: number;
    };
    /** @description 결제 신청 실패 시 요청 */
    CoinPaymentFailRequest: {
      /**
       * @description 토스 결제 에러 코드
       * @example ALREADY_PROCESSED_PAYMENT
       */
      code: string;
      /**
       * @description 토스 에러 메세지
       * @example 이미 처리된 결제 입니다.
       */
      message: string;
      /**
       * Format: uuid
       * @description 결제 Id
       * @example 8973f452-cabc-4098-bdd9-d32737c86a33
       */
      orderId: string;
    };
    /** @description 결제 confirm 요청 */
    CoinPaymentConfirmRequest: {
      /**
       * Format: uuid
       * @description 결제 Id
       * @example 8973f452-cabc-4098-bdd9-d32737c86a33
       */
      orderId: string;
      /**
       * Format: int64
       * @description 결제 금액
       * @example 10000
       */
      amount?: number;
      /**
       * @description 결제 키
       * @example asdfew20260205134206Rsdd
       */
      paymentKey: string;
    };
    /** @description 저금하기 응답 */
    CoinCreateResponse: {
      /**
       * Format: int64
       * @description 저금 내역 ID
       * @example 1
       */
      coinId?: number;
      /**
       * Format: date-time
       * @description 생성 일자
       * @example 2026-01-30T14:32:15.123+09:00
       */
      createdAt?: string;
      /**
       * Format: int64
       * @description 저금 금액
       * @example 5000
       */
      amount?: number;
      /**
       * @description 저금한 사람
       * @example 민수
       */
      name?: string;
    };
    /** @description 자동 카테고리 분류 응답 */
    CategorizeResponse: {
      /**
       * @description 요청했던 id 값
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      requestId?: string;
      /**
       * @description 분류된 대분류
       * @example 의료비
       */
      mainCategory?: string;
      /**
       * @description 분류된 소분류
       * @example 수술비
       */
      subCategory?: string | null;
    };
    /** @description 자동 카테고리 분류 요청 */
    CategorizeRequest: {
      /**
       * @description 사용한 지출내역
       * @example 뚱이 허리 수술
       */
      usage: string;
      /**
       * @description 요청 id 값
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      requestId: string;
    };
    ConnectionTokenResponse: {
      connectionToken?: string;
    };
    /** @description 토큰 재발급 요청 */
    AuthTokenRefreshRequest: {
      /**
       * @description 만료된 Access Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
       */
      accessToken: string;
      /**
       * @description 유효한 Refresh Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.cThIIoDvwdueQB4NgjKBAI
       */
      refreshToken: string;
    };
    /** @description 토큰 재발급 응답 */
    AuthTokenRefreshResponse: {
      /**
       * @description 새로 발급된 Access Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
       */
      accessToken?: string;
      /**
       * @description 새로 발급된 Refresh Token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.cThIIoDvwdueQB4NgjKBAI
       */
      refreshToken?: string;
      /**
       * @description Refresh Token 만료까지 남은 시간 (ISO-8601 Duration 형식)
       * @example PT168H
       */
      refreshTokenExpiration?: string;
    };
    /** @description 로그인 요청 */
    AuthLoginRequest: {
      /**
       * @description Google OAuth 엑세스 토큰
       * @example google access
       */
      accessToken: string;
      /**
       * @description 초대 코드 url(없을 시 null)
       * @example https://moong.site/invite/123
       */
      inviteUrl?: string;
    };
    /** @description 로그인 응답 */
    AuthLoginResponse: {
      /**
       * @description 초대된 회원인지 여부
       * @example true
       */
      isInvited?: boolean;
      /**
       * @description 신규회원 여부
       * @example true
       */
      isNew?: boolean;
      /**
       * @description 그룹 소속 여부
       * @example true
       */
      hasGroup?: boolean;
      /**
       * Format: int64
       * @description 회원 ID
       * @example 102345
       */
      memberId?: number;
      /**
       * @description 임의 생성된 회원 닉네임
       * @example 행복한펭귄42
       */
      name?: string;
      /**
       * @description 회원 프로필 URL
       * @example https://cdn.example.com/profile/default_01.png
       */
      imageUrl?: string;
      /**
       * @description 강아지 이름 (초대되지 않은 경우 null)
       * @example 코코
       */
      petName?: string | null;
      /**
       * @description 견종 코드 (초대되지 않은 경우 null)
       * @example BEA
       * @enum {string|null}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC"
        | null;
      /**
       * @description 강아지 성별 (M: 남아, F: 여아, 초대되지 않은 경우 null)
       * @example M
       * @enum {string|null}
       */
      gender?: "M" | "F" | null;
      /** @example 2026-02 */
      birthDate?: string;
    };
    /** @description 회원 프로필 업데이트 요청 */
    MemberUpdateProfileRequest: {
      /**
       * @description 회원 프로필
       * @example http://~~~
       */
      memberImageUrl: string;
    };
    MemberUpdateProfileResponse: {
      /** Format: int64 */
      memberId?: number;
      memberName?: string;
      memberImageUrl?: string;
    };
    /** @description 회원 닉네임 업데이트 요청 */
    MemberUpdateNameRequest: {
      /**
       * @description 회원 닉네임
       * @example john koo
       */
      memberName: string;
    };
    MemberUpdateNameResponse: {
      /** Format: int64 */
      memberId?: number;
      memberName?: string;
      memberImageUrl?: string;
    };
    /** @description 저금통 목표 금액 변경 요청 */
    BankUpdateRequest: {
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 1500000
       */
      target?: number;
    };
    /** @description 저금통 목표 금액 변경 응답 */
    BankUpdateResponse: {
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 1500000
       */
      target?: number;
    };
    MemberExpenseUpsertRequest: {
      /**
       * @description 신규 생성 여부 (true: 새 소비내역 생성, false: 기존 소비내역 수정)
       * @example true
       */
      isNew?: boolean;
      /**
       * Format: int64
       * @description 소비내역 ID
       * @example 1
       */
      expenseId?: number;
      /**
       * Format: date
       * @description 소비 날짜
       * @example 2026-01-20
       */
      spentAt: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 15000
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory: string;
      /**
       * @description 소분류 카테고리
       * @example 약/처방
       */
      subCategory?: string;
      /**
       * @description 메모
       * @example 정기 구매
       */
      memo?: string;
    };
    MemberExpensesUpsertRequest: {
      /** @description 생성 및 수정할 소비내역 목록 */
      expenses?: components["schemas"]["MemberExpenseUpsertRequest"][];
      /** @description 삭제할 소비내역 ID 목록 */
      deletedIds?: number[];
    };
    /** @description 소비내역 단건 응답 DTO */
    MemberExpenseResponse: {
      /**
       * Format: int64
       * @description 소비내역 ID
       * @example 1
       */
      expenseId?: number;
      /**
       * Format: date
       * @description 소비 날짜
       * @example 2026-01-20
       */
      spentAt?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 15000
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 소분류 카테고리
       * @example 약/처방
       */
      subCategory?: string;
      /**
       * @description 메모
       * @example 정기 구매
       */
      memo?: string;
      /**
       * Format: date-time
       * @description 수정일자
       * @example 2026-01-20T14:32:15.123+09:00
       */
      modifiedAt?: string;
    };
    /** @description 멤버 소비내역 기간 조회 응답 V2 */
    MemberExpensesPeriodResponseV2: {
      /**
       * Format: int64
       * @description 조회된 소비내역 총 금액
       * @example 45000
       */
      total?: number;
      /**
       * Format: int64
       * @description 페이지 번호
       * @example 1
       */
      page?: number;
      /**
       * Format: int64
       * @description 페이지 사이즈
       * @example 10
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 유무
       * @example true
       */
      hasNext?: boolean;
      /** @description 조회한 소비 내역 목록 */
      expenses?: components["schemas"]["MemberExpenseResponse"][];
    };
    /** @description 반려동물 정보 응답 */
    PetReadResponse: {
      /**
       * Format: int64
       * @description 반려동물 아이디
       * @example 1
       */
      petId?: number;
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName?: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender?: "M" | "F";
      /** @example 2026-02 */
      birthDate?: string;
      /**
       * @description 거주 시
       * @example 서울시
       */
      city?: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example [
       *       "OCU",
       *       "MUS"
       *     ]
       */
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 알림 내용 */
    GroupEventPayload: Record<string, never>;
    /** @description 알림 내역 조회 응답 */
    NotificationReadResponse: {
      /**
       * Format: int64
       * @description 마지막으로 확인한 알림 ID(조회 시작 시점 기준). 알림이 없으면 null
       */
      lastSeenNotificationId?: number;
      /**
       * Format: int32
       * @description 현재 페이지 인덱스(0부터 시작)
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 페이지 사이즈
       * @example 10
       */
      size?: number;
      /**
       * @description 다음 페이지 존재 여부
       * @example true
       */
      hasNext?: boolean;
      /** @description 알림 목록 */
      notifications?: components["schemas"]["NotificationResponse"][];
    };
    /** @description 사용자에게 표시되는 개별 알림 정보 */
    NotificationResponse: {
      /**
       * Format: int64
       * @description 알림 ID
       * @example 1
       */
      notificationId?: number;
      payload?: components["schemas"]["GroupEventPayload"];
      /**
       * @description 이벤트 종류
       * @example SAVING
       * @enum {string}
       */
      eventType?: "SAVING" | "NUDGE" | "AI_ADVICE_CREATED";
      /**
       * Format: date-time
       * @description 생성 시간
       * @example 2026-01-30T14:32:15.123+09:00
       */
      createdAt?: string;
    };
    /** @description 알림 개수 조회 응답 */
    NotificationCountResponse: {
      /**
       * Format: int64
       * @description 삭제되지 않은 알림 개수
       */
      count?: number;
    };
    /** @description 회원 정보 응답 */
    MemberInfoResponse: {
      /**
       * @description 회원 닉네임
       * @example 커피내기장인 콜리
       */
      memberName?: string;
      /**
       * @description 회원 이메일
       * @example kkwoo001021@naver.com
       */
      memberEmail?: string;
      /**
       * @description 회원 프로필 이미지 url
       * @example S3 image Url
       */
      memberImageUrl?: string;
    };
    /** @description 질병별 통계 정보 */
    MedicalStatisticsResponse: {
      /**
       * @description 질병 코드
       * @example DER
       * @enum {string}
       */
      disease?:
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF";
      /**
       * @description 질병 확률 리스트
       * @example [
       *       12,
       *       14,
       *       16,
       *       18,
       *       20,
       *       22,
       *       24
       *     ]
       */
      ratios?: number[];
    };
    /** @description 그룹 질병 통계 응답 */
    PetMedicalStatisticsResponse: {
      /**
       * Format: int64
       * @description 통계 시작 연도
       * @example 2026
       */
      startYear?: number;
      /** @description 질병별 통계 목록 */
      statistics?: components["schemas"]["MedicalStatisticsResponse"][];
    };
    /** @description 그룹 의사 권장사항 응답 */
    PetMedicalInfoResponse: {
      /**
       * Format: int64
       * @description 내년 연간 예상 비용
       * @example 125000
       */
      expectedCost?: number;
      /**
       * @description AI 의료 권장사항
       * @example 내년에는 정기 건강검진 주기를 단축하고 혈액·영상 검사를 병행하는 것을 권장합니다.
       */
      advice?: string;
      /**
       * Format: int32
       * @description 내년
       * @example 2027
       */
      year?: number;
    };
    PetDiseaseRankingResponse: {
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 특정 질병의 의료비 데이터 응답 */
    TreatmentResponse: {
      /**
       * @description 진료명
       * @example 곰팡이성 피부염
       */
      name?: string;
      /**
       * @description 상세 진료 설명
       * @example 피부 트러블, 설사·구토, 세균·바이러스 감염 등
       */
      description?: string;
      /**
       * Format: int32
       * @description 최소 값
       * @example 45000
       */
      minPrice?: number;
      /**
       * Format: int32
       * @description 최대 값
       * @example 120000
       */
      maxPrice?: number;
      /**
       * Format: int32
       * @description 평균 값
       * @example 68000
       */
      averagePrice?: number;
    };
    TreatmentsResponse: {
      /** @description 특정 질병의 의료비 데이터 리스트 응답 */
      treatments?: components["schemas"]["TreatmentResponse"][];
    };
    /** @description 모임원 정보 조회 응답 */
    GroupCrewResponse: {
      /**
       * @description 요청한 사용자 이름
       * @example 김건우
       */
      memberName?: string;
      /**
       * @description 초대 URL
       * @example https://moong.site/invite/ABCD1234
       */
      inviteUrl?: string;
      /**
       * @description 모임원 닉네임 목록
       * @example [
       *       "두john쿠",
       *       "용용이",
       *       "헬창재민"
       *     ]
       */
      crews?: string[];
    };
    BankInfoResponse: {
      /**
       * Format: int64
       * @description 저금통 ID
       * @example 1
       */
      bankId?: number;
      /**
       * Format: int64
       * @description 현재 저축 금액
       * @example 75000
       */
      current?: number;
      /**
       * Format: int64
       * @description 목표 저축 금액
       * @example 200000
       */
      target?: number;
      rankings?: components["schemas"]["BankRankingResponse"][];
    };
    /** @description 저금통 랭킹 정보 */
    BankRankingResponse: {
      /**
       * @description 사용자 이름
       * @example 건우
       */
      userName?: string;
      /**
       * Format: int64
       * @description 누적 저축 금액
       * @example 150000
       */
      total?: number;
    };
    /** @description 코인 내역 */
    CoinResponse: {
      /**
       * @description 저금한 멤버 닉네임
       * @example 코코맘
       */
      name?: string;
      /**
       * Format: int64
       * @description 저금한 금액
       * @example 5000
       */
      amount?: number;
      /**
       * Format: date-time
       * @description 생성 일자
       * @example 2026-01-30T14:32:15.123+09:00
       */
      createdAt?: string;
    };
    /** @description 저금통 코인 내역 조회 응답 */
    CoinsResponse: {
      /** @description 저금통 코인 내역 리스트 */
      coins?: components["schemas"]["CoinResponse"][];
    };
    /** @description 멤버 소비내역 기간 조회 응답 */
    MemberExpensesPeriodResponse: {
      /**
       * Format: int64
       * @description 조회된 소비내역 총 금액
       * @example 45000
       */
      total?: number;
      /** @description 조회한 소비 내역 목록 */
      expenses?: components["schemas"]["MemberExpenseResponse"][];
    };
    GroupExpenseResponse: {
      /**
       * Format: int64
       * @description 소비 내역 ID
       * @example 1
       */
      expenseId?: number;
      /**
       * Format: date
       * @description 소비 날짜
       * @example 2026-01-20
       */
      spendAt?: string;
      /**
       * @description 사용자 닉네임
       * @example 코코맘
       */
      nickName?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 18500
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 소분류 카테고리
       * @example 약/처방
       */
      subCategory?: string | null;
      /**
       * @description 메모 (입력하지 않은 경우 null)
       * @example 내과 진료 후 약국
       */
      memo?: string | null;
      /**
       * Format: date-time
       * @description 수정 일시 (ISO-8601, 타임존 포함)
       * @example 2026-01-20T14:32:15.123+09:00
       */
      modifiedAt?: string;
    };
    GroupExpensesResponse: {
      /** Format: int64 */
      total?: number;
      expenses?: components["schemas"]["GroupExpenseResponse"][];
    };
    /** @description 캘린더 특정 일자 소비내역 */
    GroupExpenseDailyResponse: {
      /**
       * @description 멤버 닉네임
       * @example 코코맘
       */
      nickname?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 15000
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 대분류 카테고리
       * @example 약/처방
       */
      subCategory?: string;
    };
    /** @description 캘린더에서 선택한 특정 날짜의 그룹 소비 내역 응답 */
    GroupExpensesDailyResponse: {
      /**
       * Format: int64
       * @description 그룹원의 특정 일자 총 지출
       * @example 11000
       */
      total?: number;
      /** @description 해당 날짜의 그룹 소비 내역 목록 */
      expenses?: components["schemas"]["GroupExpenseDailyResponse"][];
    };
    MedicalAnalysisResponse: {
      /** @enum {string} */
      subCategory?:
        | "CONSULTATION"
        | "VACCINATION"
        | "MEDICATION"
        | "EXAMINATION"
        | "SURGERY_HOSPITALIZATION"
        | "OTHER_MEDICAL";
      /** Format: int64 */
      cost?: number;
      /** Format: double */
      ratio?: number;
    };
    MedicalCategoryAnalysisResponse: {
      /** Format: int64 */
      totalMedical?: number;
      medicalAnalysis?: components["schemas"]["MedicalAnalysisResponse"][];
    };
    /** @description 카테고리별 소비 분석 응답 */
    CategoryAnalysisResponse: {
      /**
       * Format: int64
       * @description 전체 소비 금액 합계
       * @example 320000
       */
      total?: number;
      /** @description 카테고리별 소비 분석 목록 (소비 금액 기준 내림차순) */
      categoryAnalysis?: components["schemas"]["CategoryCostResponse"][];
    };
    /** @description 카테고리별 소비 금액 및 비율 정보 */
    CategoryCostResponse: {
      /**
       * @description 소비 카테고리 식별자
       * @example 의료비
       */
      category?: string;
      /**
       * Format: int64
       * @description 해당 카테고리의 총 소비 금액
       * @example 185000
       */
      cost?: number;
      /**
       * Format: double
       * @description 전체 소비 대비 해당 카테고리의 소비 비율 (소수점 첫째 자리까지)
       * @example 42.3
       */
      ratio?: number;
    };
    /** @description 지난달 소비내역 통계 응답 */
    LastMonthComparisonResponse: {
      /**
       * Format: int32
       * @description 전월 대비 총 지출 변동률 (단위: %)
       * @example -26
       */
      totalRatio?: number | null;
      /**
       * Format: int32
       * @description 전월 대비 의료비 지출 변동률 (단위: %)
       * @example 14
       */
      medicalRatio?: number | null;
      /**
       * @description 강아지 이름
       * @example 코코
       */
      petName?: string;
      /**
       * @description 강아지 사진 URL
       * @example https://avatars.githubusercontent.com/u/148152234?v=4
       */
      petImageUrl?: string;
    };
    /** @description 저금통 깨기 응답 */
    BankBreakResponse: {
      /**
       * Format: int64
       * @description 저금통을 유지한 총 일수
       * @example 42
       */
      days?: number;
      /**
       * @description 저금통을 깼을 때 출력되는 축하 메시지
       * @example 축하해요! 저금통이 열렸어요!
       */
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  findPetInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 반려동물 정보 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PetReadResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 반려동물 정보가 없을 때 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updatePetInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["PetUpdateRequest"];
      };
    };
    responses: {
      /** @description 반려동물 정보 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PetUpdateResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 반려동물 정보가 없을 때 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  savePet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["PetCreateRequest"];
      };
    };
    responses: {
      /** @description 반려동물 등록 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetCreateResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  participate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["PetGroupParticipateRequest"];
      };
    };
    responses: {
      /** @description 그룹 참여 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetGroupParticipateResponse"];
        };
      };
      /**
       * @description 다음과 같은 경우 그룹 참여가 실패합니다.
       *     - 잘못된 초대 URL
       *     - 이미 참여한 그룹
       *     - 그룹 정원이 모두 찬 경우
       *     - 이미 다른 그룹에 참여 중인 경우 (2명 이상 구성원 보유)
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findBankInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 정보 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BankInfoResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createBank: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["BankCreateRequest"];
      };
    };
    responses: {
      /** @description 저금통 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["BankCreateResponse"];
        };
      };
      /** @description 저금통이 이미 존재하는 경우 저금통 생성에 실패합니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  breakBank: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 깨기 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["BankBreakResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateBank: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["BankUpdateRequest"];
      };
    };
    responses: {
      /** @description 저금통 목표 금액 변경 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["BankUpdateResponse"];
        };
      };
      /**
       * @description - 현재 저금통에 쌓인 금액보다 낮은 금액으로 변경 시도
       *     - 목표 금액이 1000만원 초과
       *     - 목표 금액이 0원 이하
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createGroupNudge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 재촉하기 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findCoins: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 코인 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoinsResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createCoinPayment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 결제 요청 전 검증을 위한 금액 데이터 저장 요청 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["CoinCreateRequest"];
      };
    };
    responses: {
      /** @description 실제 결제 전 금액 요청 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["CoinPaymentCreateResponse"];
        };
      };
      /**
       * @description - 저금하기 금액이 0원 이하
       *     - 이미 저금통 목표 금액 도달
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  paymentFailure: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 결제 실패 시 요청 데이터 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["CoinPaymentFailRequest"];
      };
    };
    responses: {
      /** @description 결제 실패 처리 완료 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description - 요청 데이터(orderId, amount 등) 형식이 올바르지 않음 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 해당 주문 번호(orderId)로 저장된 결제 정보를 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  paymentSuccess: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 결제 성공 시 요청 데이터 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["CoinPaymentConfirmRequest"];
      };
    };
    responses: {
      /** @description 결제 확정을 성공하여 저금에 성공합니다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["CoinCreateResponse"];
        };
      };
      /**
       * @description - 유효하지 않은 결제 요청
       *     - 결제 확정 금액이 주문 금액과 일치하지 않는 경우
       *     - 이미 처리 중이거나 완료된 결제 요청
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 코인 결제 내역을 찾을 수 없음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMemberExpensesByPeriod: {
    parameters: {
      query: {
        /**
         * @description 조회 시작일 (yyyy-MM-dd)
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료일 (yyyy-MM-dd)
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 개인 소비 내역 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberExpensesPeriodResponse"];
        };
      };
      /** @description 시작일은 종료일보다 늦을 수 없습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  categorizeMemberExpenses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 자동카테고리 분류 요청 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["CategorizeRequest"];
      };
    };
    responses: {
      /** @description 카테고리 분류 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["CategorizeResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  upsertMemberExpenses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 수정, 추가, 삭제된 소비 내역들 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["MemberExpensesUpsertRequest"];
      };
    };
    responses: {
      /** @description 생성, 수정, 삭제 성공 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  issueConnectionToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 유효한 Connection 토큰을 발급합니다. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ConnectionTokenResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["AuthTokenRefreshRequest"];
      };
    };
    responses: {
      /** @description 토큰 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["AuthTokenRefreshResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie: {
        /** @description 무효화할 Refresh Token */
        refreshToken: string;
      };
    };
    requestBody?: never;
    responses: {
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["AuthLoginRequest"];
      };
    };
    responses: {
      /** @description 로그인 성공 */
      201: {
        headers: {
          /** @description Bearer {accessToken} */
          Authorization?: string;
          /** @description refreshToken={refreshToken}; */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["AuthLoginResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 회원 프로필 업데이트 요청 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["MemberUpdateProfileRequest"];
      };
    };
    responses: {
      /** @description 회원 프로필 업데이트 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberUpdateProfileResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateName: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 회원 닉네임 업데이트 요청 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["MemberUpdateNameRequest"];
      };
    };
    responses: {
      /** @description 회원 닉네임 업데이트 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberUpdateNameResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  sendThisMonthReport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 발송 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  refresh_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getMemberExpensesByPeriodV2: {
    parameters: {
      query: {
        /**
         * @description 조회 시작일 (yyyy-MM-dd)
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료일 (yyyy-MM-dd)
         * @example 2026-01-31
         */
        endDate: string;
        /**
         * @description 메인 카테고리 필터 (선택)
         * @example 사료/간식
         */
        mainCategory?: string;
        lastRowId?: number;
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 개인 소비 내역 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberExpensesPeriodResponseV2"];
        };
      };
      /** @description 시작일은 종료일보다 늦을 수 없습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findNotification: {
    parameters: {
      query?: {
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 알림 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["NotificationReadResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 알림 수신 정보를 찾을 수 없습니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteNotification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 다중 알림 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  countNotification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 알림 개수 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["NotificationCountResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findMember: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 회원정보 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberInfoResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  subscribe: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 연결 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": unknown;
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findGroupDieseaseStatistics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetMedicalStatisticsResponse"];
        };
      };
    };
  };
  getGroupMedicalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 그룹 의사 권장사항 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetMedicalInfoResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description AI 의사 권장사항 생성 중 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findPetDiseaseRanking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 사용자의 그룹에 속한 펫의 발병확률 순 질병 목록 반환 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetDiseaseRankingResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getTreatment: {
    parameters: {
      query: {
        disease:
          | "DER"
          | "MUS"
          | "NEU"
          | "OCU"
          | "RES"
          | "CAR"
          | "HEM"
          | "GAS"
          | "URI"
          | "REP"
          | "END"
          | "INF";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 특정 질병의 의료비 데이터 리스트 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["TreatmentsResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCrews: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 모임원 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupCrewResponse"];
        };
      };
      /**
       * @description 다음과 같은 경우 조회가 실패합니다.
       *             - 사용자가 그룹에 속해있지 않은 경우
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findGroupExpenses: {
    parameters: {
      query: {
        /**
         * @description 조회 시작 날짜
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료 날짜
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 모임 소비 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupExpensesResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findGroupDailyExpenses: {
    parameters: {
      query: {
        /**
         * @description 조회 날짜
         * @example 2026-01-01
         */
        spentAt: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 캘린더 특정 날짜 그룹 소비 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupExpensesDailyResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findMedicalCategoryAnalysis: {
    parameters: {
      query: {
        /**
         * @description 조회 시작 날짜
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료 날짜
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 의료비 분석 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MedicalCategoryAnalysisResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findCategoryAnalysis: {
    parameters: {
      query: {
        /**
         * @description 조회 시작 날짜
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료 날짜
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 카테고리별 소비 분석 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["CategoryAnalysisResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compareLastMonthExpense: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 지난달 소비 내역 통계 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["LastMonthComparisonResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  validate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 유효 토큰 */
      200: {
        headers: {
          /** @description Bearer {accessToken} */
          Authorization?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteNotification_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notificationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 알림 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 해당 크루의 알림 정보를 찾을 수 없습니다. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
