/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/pet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 반려동물 정보 조회
     * @description 로그인한 회원의 반려동물 정보를 조회합니다.
     */
    get: operations["findPetInfo"];
    put?: never;
    /**
     * 반려동물 등록
     * @description 회원이 새로운 반려동물을 등록합니다.
     */
    post: operations["savePet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/particiapte": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 그룹 초대 참여
     * @description 초대 URL을 통해 펫 그룹에 참여합니다.
     */
    post: operations["participate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/bank": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 저금통 정보 조회
     * @description 저금통의 현재, 목표 금액을 반환합니다
     */
    get: operations["findBankInfo"];
    put?: never;
    /**
     * 저금통 생성
     * @description 로그인한 사용자가 속한 모임에
     *     목표 금액을 가진 저금통을 생성합니다.
     */
    post: operations["createBank"];
    /**
     * 저금통 깨기
     * @description 저금통을 깨고, 저축 기간과 축하 메시지를 반환합니다.
     */
    delete: operations["breakBank"];
    options?: never;
    head?: never;
    /**
     * 저금통 목표 금액 변경
     * @description 저금통 목표 금액을 변경하고, 변경된 금액을 반환합니다.
     */
    patch: operations["updateBank"];
    trace?: never;
  };
  "/api/group/bank/coins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임가계부 저금통 코인 내역 반환
     * @description 저금통의 코인 내역의 정보들의 리스트를 반환합니다.
     */
    get: operations["findCoins"];
    put?: never;
    /**
     * 저금하기
     * @description 원하는 금액만큼을 저금합니다.
     */
    post: operations["createCoin"];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 저금통 목표 금액 변경
     * @description 저금통 목표 금액을 변경하고, 변경된 금액을 반환합니다.
     */
    patch: operations["updateBank"];
    trace?: never;
  };
  "/api/expenses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 기간 내의 개인 소비내역 반환
     * @description 시작일/종료일을 기준으로 기간 내 개인 소비내역을 최신순으로 조회합니다.
     */
    get: operations["getMemberExpensesByPeriod"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 개인 소비 지출 입력
     * @description 개인 소비 내역을 생성하거나 수정하고, 삭제 대상 내역은 함께 제거합니다.
     */
    patch: operations["upsertMemberExpenses"];
    trace?: never;
  };
  "/api/expenses/compare/last-month": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지난달 대비 비교 데이터 조회
     * @description 총지출/의료비 비율, 반려동물 이름·이미지 URL 반환
     */
    get: operations["getCompareLastMonth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/member": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["findMember"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/statistics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 그룹 질병 통계 조회
     * @description 회원이 속한 그룹의 질병별 연도 통계 데이터를 조회합니다.
     */
    get: operations["findGroupDieseaseStatistics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 그룹 의사 권장사항 반환
     * @description 로그인한 사용자가 속한 모임의 반려동물 AI 의료 권장사항과
     *     내년 연간 예상 비용을 조회합니다.
     */
    get: operations["getGroupMedicalInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/disease": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 올해 기준 발병확률 순 질병 목록 반환
     * @description 사용자의 펫 데이터를 통해 가장 주의해야할 질병부터 순서대로 반환합니다.
     */
    get: operations["findPetDiseaseRanking"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/medical/disease/cost": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 질병의 의료비 데이터 리스트 반환
     * @description 특정 질병의 치료법들에 대해 각 치료법의 진료명, 상세 진료 설명,
     *     그리고 치료비의 최소·최대·평균값을 조회합니다.
     */
    get: operations["getTreatment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/group/bank/coins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임가계부 저금통 코인 내역 반환
     * @description 저금통의 코인 내역의 정보들의 리스트를 반환합니다.
     */
    get: operations["findCoins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임 소비 내역 조회
     * @description 로그인한 사용자가 속한 모임의 소비 내역을
     *     지정한 기간(startDate ~ endDate) 기준으로 조회합니다.
     *     spendAt 기준 내림차순 > modifiedAt 기준 내림차순 정렬됩니다.
     */
    get: operations["findGroupExpenses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group/date": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 캘린더 일자별 조회
     * @description 캘린더에서 특정 날짜(spentAt)에 해당하는 그룹 소비 내역 리스트를 조회합니다.
     *     spentAt 기준 내림차순, modifiedAt 기준 내림차순으로 정렬됩니다.
     */
    get: operations["findGroupDailyExpenses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group/analysis/medical": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임 소비 내역 의료비 소분류 분석결과 조회
     * @description 로그인한 사용자가 속한 모임의 의료비 소분류별 내역을
     *     지정한 기간(startDate ~ endDate) 기준으로 조회합니다.
     *     소비내역이 가장 많은 카테고리별 순으로 내림차순 정렬됩니다.
     */
    get: operations["findMedicalCategoryAnalysis"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/group/analysis/category": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모임 소비 내역 카테고리 분석결과 조회
     * @description 로그인한 사용자가 속한 모임의 소비 내역을
     *     지정한 기간(startDate ~ endDate) 기준으로 조회합니다.
     *     소비내역이 가장 많은 카테고리별 순으로 내림차순 정렬됩니다.
     */
    get: operations["findCategoryAnalysis"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/compare/last-month": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 지난달 소비 내역 통계
     * @description 지난달 소비내역과 의료비 소비내역 통계를 반환합니다.
     */
    get: operations["compareLastMonthExpense"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 반려동물 생성 요청 */
    PetCreateRequest: {
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName?: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender?: "M" | "F";
      /**
       * @description 생년 월
       * @example 2026-02
       */
      birthDate?: {
        /** Format: int32 */
        year?: number;
        /** @enum {string} */
        month?:
          | "JANUARY"
          | "FEBRUARY"
          | "MARCH"
          | "APRIL"
          | "MAY"
          | "JUNE"
          | "JULY"
          | "AUGUST"
          | "SEPTEMBER"
          | "OCTOBER"
          | "NOVEMBER"
          | "DECEMBER";
        /** Format: int32 */
        monthValue?: number;
        leapYear?: boolean;
      };
      /**
       * @description 거주 시
       * @example 서울시
       */
      city?: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example OCU, MUS
       */
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 반려동물 생성 응답 */
    PetCreateResponse: {
      /**
       * Format: int64
       * @description 반려동물 아이디
       * @example 1
       */
      petId?: number;
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName?: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender?: "M" | "F";
      /**
       * @description 생년 월
       * @example 2026-02
       */
      birthDate?: {
        /** Format: int32 */
        year?: number;
        /** @enum {string} */
        month?:
          | "JANUARY"
          | "FEBRUARY"
          | "MARCH"
          | "APRIL"
          | "MAY"
          | "JUNE"
          | "JULY"
          | "AUGUST"
          | "SEPTEMBER"
          | "OCTOBER"
          | "NOVEMBER"
          | "DECEMBER";
        /** Format: int32 */
        monthValue?: number;
        leapYear?: boolean;
      };
      /**
       * @description 거주 시
       * @example 서울시
       */
      city?: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example [
       *       "OCU",
       *       "MUS"
       *     ]
       */
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    ErrorResponse: {
      code?: string;
      /** Format: int32 */
      status?: number;
      message?: string;
    };
    /** @description 그룹 초대 요청 */
    PetGroupParticipateRequest: {
      /**
       * @description 초대코드 url
       * @example https://moong.site/invite/RRJ2A2gf4I9pSxpW6F1byH2RGEweYjpmZOGasbaXvOGtHCwq
       */
      inviteUrl?: string;
    };
    /** @description 참여 완료 응답 */
    PetGroupParticipateResponse: {
      /**
       * Format: int64
       * @description 참여자 id
       * @example 1
       */
      crewId?: number;
    };
    /** @description 저금통 생성 요청 */
    BankCreateRequest: {
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 1500000
       */
      target?: number;
    };
    /** @description 저금통 생성 응답 */
    BankCreateResponse: {
      /**
       * Format: int64
       * @description 저금통 아이디
       * @example 1
       */
      bankId?: number;
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 15000000
       */
      target?: number;
    };
    /** @description 저금하기 요청 */
    CoinCreateRequest: {
      /**
       * Format: int64
       * @description 저금 금액
       * @example 5000
       */
      amount?: number;
    };
    /** @description 저금하기 응답 */
    CoinCreateResponse: {
      /**
       * Format: int64
       * @description 저금 내역 ID
       * @example 1
       */
      coinId?: number;
      /**
       * Format: date-time
       * @description 생성 일자
       * @example 2026-01-30T14:32:15.123+09:00
       */
      createdAt?: string;
      /**
       * Format: int64
       * @description 저금 금액
       * @example 5000
       */
      amount?: number;
      /**
       * @description 저금한 사람
       * @example 민수
       */
      name?: string;
    };
    /** @description 저금통 목표 금액 변경 요청 */
    BankUpdateRequest: {
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 1500000
       */
      target?: number;
    };
    /** @description 저금통 목표 금액 변경 응답 */
    BankUpdateResponse: {
      /**
       * Format: int64
       * @description 저금통 목표 금액
       * @example 1500000
       */
      target?: number;
    };
    /** @description 소비내역 단건 응답 DTO */
    MemberExpenseResponse: {
      /**
       * Format: int64
       * @description 소비내역 ID
       * @example 1
       */
      expenseId?: number;
      /**
       * Format: date
       * @description 소비 날짜
       * @example 2026-01-20
       */
      spentAt?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 15000
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 소분류 카테고리
       * @example 약/처방
       */
      subCategory?: string;
      /**
       * @description 메모
       * @example 정기 구매
       */
      memo?: string;
      /**
       * Format: date-time
       * @description 수정일자
       * @example 2026-01-20T14:32:15.123+09:00
       */
      modifiedAt?: string;
    };
    MemberExpensesUpsertResponse: {
      /** @description 생성, 수정된 소비 내역 목록 */
      expenses?: components["schemas"]["MemberExpenseResponse"][];
    };
    MemberExpenseUpsertRequest: {
      /**
       * @description 신규 생성 여부 (true: 새 소비내역 생성, false: 기존 소비내역 수정)
       * @example true
       */
      isNew?: boolean;
      /**
       * Format: int64
       * @description 소비내역 ID
       * @example 1
       */
      expenseId?: number;
      /**
       * Format: date
       * @description 소비 날짜
       * @example 2026-01-20
       */
      spentAt?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 15000
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 소분류 카테고리
       * @example 약/처방
       */
      subCategory?: string;
      /**
       * @description 메모
       * @example 정기 구매
       */
      memo?: string;
    };
    MemberExpensesUpsertRequest: {
      /** @description 생성 및 수정할 소비내역 목록 */
      expenses?: components["schemas"]["MemberExpenseUpsertRequest"][];
      /** @description 삭제할 소비내역 ID 목록 */
      deletedIds?: number[];
    };
    /** @description 반려동물 정보 응답 */
    PetReadResponse: {
      /**
       * Format: int64
       * @description 반려동물 아이디
       * @example 1
       */
      petId?: number;
      /**
       * @description 반려동물 이름
       * @example 초코
       */
      petName?: string;
      /**
       * @description 반려동물 종류
       * @example DAS
       * @enum {string}
       */
      breed?:
        | "GRE"
        | "DAL"
        | "DAS"
        | "DOB"
        | "GOL"
        | "LAB"
        | "MAL"
        | "BUL"
        | "BEA"
        | "BIC"
        | "SHE"
        | "SCH"
        | "MIL"
        | "MIS"
        | "HUS"
        | "HOU"
        | "GER"
        | "JIN"
        | "CHS"
        | "CHL"
        | "COC"
        | "TER"
        | "POM"
        | "POO"
        | "SHI"
        | "WEL"
        | "ETC";
      /**
       * @description 성별
       * @example M
       * @enum {string}
       */
      gender?: "M" | "F";
      /**
       * @description 생년 월
       * @example 2026-02
       */
      birthDate?: {
        /** Format: int32 */
        year?: number;
        /** @enum {string} */
        month?:
          | "JANUARY"
          | "FEBRUARY"
          | "MARCH"
          | "APRIL"
          | "MAY"
          | "JUNE"
          | "JULY"
          | "AUGUST"
          | "SEPTEMBER"
          | "OCTOBER"
          | "NOVEMBER"
          | "DECEMBER";
        /** Format: int32 */
        monthValue?: number;
        leapYear?: boolean;
      };
      /**
       * @description 거주 시
       * @example 서울시
       */
      city?: string;
      /**
       * @description 거주 구역
       * @example 종로구
       */
      district?: string;
      /**
       * @description 우려하는 질병 목록
       * @example [
       *       "OCU",
       *       "MUS"
       *     ]
       */
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    Member: {
      /** Format: int64 */
      id?: number;
      email: string;
      name: string;
      imageUrl?: string;
    };
    MemberInfoResponse: {
      memberName?: string;
      memberImageUrl?: string;
    };
    /** @description 그룹 질병 통계 응답 */
    GroupMedicalStatisticsResponse: {
      /**
       * Format: int64
       * @description 통계 시작 연도
       * @example 2026
       */
      startYear?: number;
      /** @description 질병별 통계 목록 */
      statistics?: components["schemas"]["MedicalStatisticsResponse"][];
    };
    /** @description 질병별 통계 정보 */
    MedicalStatisticsResponse: {
      /**
       * @description 질병 코드
       * @example DER
       * @enum {string}
       */
      disease?:
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF";
      /**
       * @description 질병 확률 리스트
       * @example [
       *       12,
       *       14,
       *       16,
       *       18,
       *       20,
       *       22,
       *       24
       *     ]
       */
      ratios?: number[];
    };
    /** @description 그룹 의사 권장사항 응답 */
    GroupMedicalInfoResponse: {
      /**
       * Format: int64
       * @description 내년 연간 예상 비용
       * @example 125000
       */
      expectedCost?: number;
      /**
       * @description AI 의료 권장사항
       * @example 내년에는 정기 건강검진 주기를 단축하고 혈액·영상 검사를 병행하는 것을 권장합니다.
       */
      advice?: string;
      /**
       * Format: int32
       * @description 내년
       * @example 2027
       */
      year?: number;
    };
    PetDiseaseRankingResponse: {
      diseases?: (
        | "DER"
        | "MUS"
        | "NEU"
        | "OCU"
        | "RES"
        | "CAR"
        | "HEM"
        | "GAS"
        | "URI"
        | "REP"
        | "END"
        | "INF"
      )[];
    };
    /** @description 특정 질병의 의료비 데이터 응답 */
    TreatmentResponse: {
      /**
       * @description 진료명
       * @example 곰팡이성 피부염
       */
      name?: string;
      /**
       * @description 상세 진료 설명
       * @example 피부 트러블, 설사·구토, 세균·바이러스 감염 등
       */
      description?: string;
      /**
       * Format: int32
       * @description 최소 값
       * @example 45000
       */
      minPrice?: number;
      /**
       * Format: int32
       * @description 최대 값
       * @example 120000
       */
      maxPrice?: number;
      /**
       * Format: int32
       * @description 평균 값
       * @example 68000
       */
      averagePrice?: number;
    };
    TreatmentsResponse: {
      /** @description 특정 질병의 의료비 데이터 리스트 응답 */
      treatments?: components["schemas"]["TreatmentResponse"][];
    };
    BankInfoResponse: {
      /**
       * Format: int64
       * @description 저금통 ID
       * @example 1
       */
      bankId?: number;
      /**
       * Format: int64
       * @description 현재 저축 금액
       * @example 75000
       */
      current?: number;
      /**
       * Format: int64
       * @description 목표 저축 금액
       * @example 200000
       */
      target?: number;
      rankings?: components["schemas"]["BankRankingResponse"][];
    };
    /** @description 저금통 랭킹 정보 */
    BankRankingResponse: {
      /**
       * @description 사용자 이름
       * @example 건우
       */
      userName?: string;
      /**
       * Format: int64
       * @description 누적 저축 금액
       * @example 150000
       */
      total?: number;
    };
    /** @description 코인 내역 */
    CoinResponse: {
      /**
       * @description 저금한 멤버 닉네임
       * @example 코코맘
       */
      name?: string;
      /**
       * Format: int64
       * @description 저금한 금액
       * @example 5000
       */
      amount?: number;
      /**
       * Format: date-time
       * @description 생성 일자
       * @example 2026-01-30T14:32:15.123+09:00
       */
      createdAt?: string;
    };
    /** @description 저금통 코인 내역 조회 응답 */
    CoinsResponse: {
      /** @description 저금통 코인 내역 리스트 */
      coins?: components["schemas"]["CoinResponse"][];
    };
    /** @description 멤버 소비내역 기간 조회 응답 */
    MemberExpensesPeriodResponse: {
      /**
       * Format: int64
       * @description 조회된 소비내역 총 금액
       * @example 45000
       */
      total?: number;
      /** @description 조회한 소비 내역 목록 */
      expenses?: components["schemas"]["MemberExpenseResponse"][];
    };
    /** @description 지난달 대비 비교 API 응답 */
    LastMonthCompareResponse: {
      /** @description 총 지출 전월 대비 비율 (%) */
      totalRatio?: number;
      /** @description 의료비 전월 대비 비율 (%) */
      medicalRatio?: number;
      /** @description 반려동물 이름 */
      petName?: string;
      /** @description 반려동물 이미지 URL */
      petImageUrl?: string;
    };
    GroupExpenseResponse: {
      /**
       * Format: int64
       * @description 소비 내역 ID
       * @example 1
       */
      expenseId?: number;
      /**
       * Format: date
       * @description 소비 날짜
       * @example 2026-01-20
       */
      spendAt?: string;
      /**
       * @description 사용자 닉네임
       * @example 코코맘
       */
      nickName?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 18500
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 소분류 카테고리
       * @example 약/처방
       */
      subCategory?: string | null;
      /**
       * @description 메모 (입력하지 않은 경우 null)
       * @example 내과 진료 후 약국
       */
      memo?: string | null;
      /**
       * Format: date-time
       * @description 수정 일시 (ISO-8601, 타임존 포함)
       * @example 2026-01-20T14:32:15.123+09:00
       */
      modifiedAt?: string;
    };
    GroupExpensesResponse: {
      /** Format: int64 */
      total?: number;
      expenses?: components["schemas"]["GroupExpenseResponse"][];
    };
    /** @description 캘린더 특정 일자 소비내역 */
    GroupExpenseDailyResponse: {
      /**
       * @description 멤버 닉네임
       * @example 코코맘
       */
      nickname?: string;
      /**
       * @description 사용 내역
       * @example 감기약 및 처방약 구매
       */
      usage?: string;
      /**
       * Format: int64
       * @description 소비 금액
       * @example 15000
       */
      cost?: number;
      /**
       * @description 대분류 카테고리
       * @example 병원비
       */
      mainCategory?: string;
      /**
       * @description 대분류 카테고리
       * @example 약/처방
       */
      subCategory?: string;
    };
    /** @description 캘린더에서 선택한 특정 날짜의 그룹 소비 내역 응답 */
    GroupExpensesDailyResponse: {
      /**
       * Format: int64
       * @description 그룹원의 특정 일자 총 지출
       * @example 11000
       */
      total?: number;
      /** @description 해당 날짜의 그룹 소비 내역 목록 */
      expenses?: components["schemas"]["GroupExpenseDailyResponse"][];
    };
    MedicalAnalysisResponse: {
      subCategory?: string;
      /** Format: int64 */
      cost?: number;
      /** Format: double */
      ratio?: number;
    };
    MedicalCategoryAnalysisResponse: {
      /** Format: int64 */
      totalMedical?: number;
      medicalAnalysis?: components["schemas"]["MedicalAnalysisResponse"][];
    };
    /** @description 카테고리별 소비 분석 응답 */
    CategoryAnalysisResponse: {
      /**
       * Format: int64
       * @description 전체 소비 금액 합계
       * @example 320000
       */
      total?: number;
      /** @description 카테고리별 소비 분석 목록 (소비 금액 기준 내림차순) */
      categoryAnalysis?: components["schemas"]["CategoryCostResponse"][];
    };
    /** @description 카테고리별 소비 금액 및 비율 정보 */
    CategoryCostResponse: {
      /**
       * @description 소비 카테고리 식별자
       * @example 의료비
       */
      category?: string;
      /**
       * Format: int64
       * @description 해당 카테고리의 총 소비 금액
       * @example 185000
       */
      cost?: number;
      /**
       * Format: double
       * @description 전체 소비 대비 해당 카테고리의 소비 비율 (소수점 첫째 자리까지)
       * @example 42.3
       */
      ratio?: number;
    };
    /** @description 지난달 소비내역 통계 응답 */
    LastMonthComparisonResponse: {
      /**
       * Format: int32
       * @description 전월 대비 총 지출 변동률 (단위: %)
       * @example -26
       */
      totalRatio?: number | null;
      /**
       * Format: int32
       * @description 전월 대비 의료비 지출 변동률 (단위: %)
       * @example 14
       */
      medicalRatio?: number | null;
      /**
       * @description 강아지 이름
       * @example 코코
       */
      petName?: string;
      /**
       * @description 강아지 사진 URL
       * @example https://avatars.githubusercontent.com/u/148152234?v=4
       */
      petImageUrl?: string;
    };
    /** @description 저금통 깨기 응답 */
    BankBreakResponse: {
      /**
       * Format: int64
       * @description 저금통을 유지한 총 일수
       * @example 42
       */
      days?: number;
      /**
       * @description 저금통을 깼을 때 출력되는 축하 메시지
       * @example 축하해요! 저금통이 열렸어요!
       */
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  findPetInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 반려동물 정보 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PetReadResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 반려동물 정보가 없을 때 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  savePet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["PetCreateRequest"];
      };
    };
    responses: {
      /** @description 반려동물 등록 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetCreateResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  participate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["PetGroupParticipateRequest"];
      };
    };
    responses: {
      /** @description 그룹 참여 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetGroupParticipateResponse"];
        };
      };
      /**
       * @description 다음과 같은 경우 그룹 참여가 실패합니다.
       *     - 잘못된 초대 URL
       *     - 이미 참여한 그룹
       *     - 그룹 정원이 모두 찬 경우
       *     - 이미 다른 그룹에 참여 중인 경우 (2명 이상 구성원 보유)
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findBankInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 정보 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BankInfoResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createBank: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["BankCreateRequest"];
      };
    };
    responses: {
      /** @description 저금통 생성 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["BankCreateResponse"];
        };
      };
      /** @description 저금통이 이미 존재하는 경우 저금통 생성에 실패합니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  breakBank: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 깨기 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["BankBreakResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateBank: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["BankUpdateRequest"];
      };
    };
    responses: {
      /** @description 저금통 목표 금액 변경 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["BankUpdateResponse"];
        };
      };
      /**
       * @description - 현재 저금통에 쌓인 금액보다 낮은 금액으로 변경 시도
       *     - 목표 금액이 1000만원 초과
       *     - 목표 금액이 0원 이하
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findCoins: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 코인 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoinsResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createCoin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["CoinCreateRequest"];
      };
    };
    responses: {
      /** @description 저금 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["CoinCreateResponse"];
        };
      };
      /**
       * @description - 저금하기 금액이 0원 이하
       *     - 이미 저금통 목표 금액 도달
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMemberExpensesByPeriod: {
    parameters: {
      query: {
        /**
         * @description 조회 시작일 (yyyy-MM-dd)
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료일 (yyyy-MM-dd)
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 개인 소비 내역 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberExpensesPeriodResponse"];
        };
      };
      /** @description 시작일은 종료일보다 늦을 수 없습니다. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCompareLastMonth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 지난달 대비 비교 데이터 반환 성공 */
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["LastMonthCompareResponse"];
        };
      };
      /** @description 실패 - MEMBER_ID_MISMATCH 등 */
      400: {
        headers: { [name: string]: unknown };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 인증되지 않은 사용자(유효하지 않은 memberId) */
      401: {
        headers: { [name: string]: unknown };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 존재하지 않은 테이블 */
      404: {
        headers: { [name: string]: unknown };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: { [name: string]: unknown };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  upsertMemberExpenses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 수정, 추가, 삭제된 소비 내역들 */
    requestBody: {
      content: {
        "application/json;charset=UTF-8": components["schemas"]["MemberExpensesUpsertRequest"];
      };
    };
    responses: {
      /** @description 생성, 수정, 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberExpensesUpsertResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findMember: {
    parameters: {
      query: {
        member: components["schemas"]["Member"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MemberInfoResponse"];
        };
      };
    };
  };
  findGroupDieseaseStatistics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupMedicalStatisticsResponse"];
        };
      };
    };
  };
  getGroupMedicalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 그룹 의사 권장사항 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupMedicalInfoResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findPetDiseaseRanking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 사용자의 그룹에 속한 펫의 발병확률 순 질병 목록 반환 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["PetDiseaseRankingResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getTreatment: {
    parameters: {
      query: {
        disease:
          | "DER"
          | "MUS"
          | "NEU"
          | "OCU"
          | "RES"
          | "CAR"
          | "HEM"
          | "GAS"
          | "URI"
          | "REP"
          | "END"
          | "INF";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 특정 질병의 의료비 데이터 리스트 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["TreatmentsResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findCoins: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 저금통 코인 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoinsResponse"];
        };
      };
      /** @description 저금통이 아직 존재하지 않음 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findGroupExpenses: {
    parameters: {
      query: {
        /**
         * @description 조회 시작 날짜
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료 날짜
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 모임 소비 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupExpensesResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findGroupDailyExpenses: {
    parameters: {
      query: {
        /**
         * @description 조회 날짜
         * @example 2026-01-01
         */
        spentAt: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 캘린더 특정 날짜 그룹 소비 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["GroupExpensesDailyResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findMedicalCategoryAnalysis: {
    parameters: {
      query: {
        /**
         * @description 조회 시작 날짜
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료 날짜
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 의료비 분석 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["MedicalCategoryAnalysisResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  findCategoryAnalysis: {
    parameters: {
      query: {
        /**
         * @description 조회 시작 날짜
         * @example 2026-01-01
         */
        startDate: string;
        /**
         * @description 조회 종료 날짜
         * @example 2026-01-31
         */
        endDate: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 카테고리별 소비 분석 내역 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["CategoryAnalysisResponse"];
        };
      };
      /** @description 인증되지 않은 사용자 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description 서버 오류 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compareLastMonthExpense: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 지난달 소비 내역 통계 반환 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json;charset=UTF-8": components["schemas"]["LastMonthComparisonResponse"];
        };
      };
    };
  };
}
