const WALL_THICKNESS = 36;

export const PIGGY_BANK = {
  GRAVITY: 1.1,
  DEFAULT_WIDTH: 800,
  DEFAULT_HEIGHT: 420,
  WALL_THICKNESS,
  WALL_OFFSET: WALL_THICKNESS / 2,
  FLOOR_OVERFLOW: 80,
  MIN_RADIUS: 30,
  SCALE_BASE: 268,
  BALL_RESTITUTION: 0.2,
  BALL_FRICTION: 0.1,
  BALL_DROP_Y: 20,
  LABEL_FILL_COLOR: "rgba(0, 0, 0, 0.5)",
  LABEL_FONT_RATIO: 0.25,
  LABEL_FONT_MIN: 10,
  LABEL_FONT_MAX: 30,
  LABEL_RADIUS_RATIO: 0.7,
  COIN_TEXTURE_PATH: "/images/img_coin_texture.png",
  DRAG_STIFFNESS: 0.8,
} as const;

export const DROP_DELAY = 600;
export const MAX_DROP_DURATION = 5000;
