management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    enabled: true
    #검색
    filter: true
    deep-linking: true
    #정렬
    tags-sorter: alpha
    operations-sorter: alpha
    #UX
    display-request-duration: true
    disable-swagger-default-url: true
invite:
  key: ${INVITE_AES_KEY}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER_IP}:3306/moong?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false

logging:
  file:
    path: logs
    name: app.log

  logback:
    rollingpolicy:
      max-file-size: 5MB #한 파일의 최대 크기
      max-history: 30 #최대 보관 일자(최근 30일간 기록까지만 저장)
      total-size-cap: 150MB #전체 차지가능한 디스크 용량

slack:
  webhook-url: ${ERROR_SLACK_WEBHOOK_URL:}

category-classification:
  system-prompt: |
    유저가 입력한 소비 내역의 카테고리를 다음 중에 분류해    
    
    조건:
    - mainCategory는 대분류고 subCategory는 소분류야
    - mainCategory는 '사료/간식', '의료비', `물품구매비`, `미용`, `기타` 중 하나로 분류해줘
    - mainCategory가 `의료비`가 아닌 경우 subCategory에는 null을 반환해.   
    - mainCategory가 `의료비`일 경우 subCategory도 생성해줘     
    - mainCategory가 의료비인 경우 subCategory는 [진료비, 예방접종, 약/처방, 검사비, 수술/입원, 기타 의료비] 중 하나로 분류해줘

  prompt-template: |
    반려동물 소비 카테고리 대분류 -> mainCategory
    소비 카테고리 소분류 -> subCategory
    
    유저 입력: {input}

  format-message: |
    응답은 반드시 다음 JSON 스키마에 맞춰 정확한 JSON 형식으로 제공해주세요(맨 처음에 ```json 같은 것도 절대 포함하지 마세요).
    
    {
      "mainCategory": "string",
      "subCategory": "string"
    }
    
    응답에는 JSON만 포함하고, 다른 텍스트나 설명은 포함하지 마세요.
    JSON 형식으로만 응답해야 하며, 내가 그대로 파싱할 예정입니다.

openai:
  base-url: https://api.openai.com/v1
  secret-key: ${OPEN_AI_KEY}

toss:
  secret-key: ${TOSS_SECRET_KEY}
  base-url: https://api.tosspayments.com/v1/payments
  password:

jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_token_expiration: ${JWT_ACCESS_EXPIRATION}
  refresh_token_expiration: ${JWT_REFRESH_EXPIRATION}

